[package]
name = "trading-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
description = "trading_core Canisterの雛形"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
candid.workspace = true
db = { path = "../db" }
ic-cdk.workspace = true
