#!/usr/bin/env python3
"""Compose the five existing Candid contracts for the embedded Canister."""

from collections import Counter
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCES = {
    "vault": "funds_vault",
    "core": "trading_core",
    "policy": "policy_registry",
    "guard": "control_guard",
    "journal": "send_journal",
}
METHOD = re.compile(r"^  ([A-Za-z_][A-Za-z_0-9]*) : (.*);$", re.M)
TYPE = re.compile(r"^type ([A-Za-z_][A-Za-z_0-9]*) =", re.M)

parts = {}
names = Counter()
for role, file in SOURCES.items():
    source = (ROOT / "candid" / f"{file}.did").read_text()
    types, service = source.split("service : () -> {", 1)
    # Comments in extracted Candid are documentation, not part of the interface.
    types = "\n".join(line for line in types.splitlines() if not line.lstrip().startswith("//"))
    service = "\n".join(line for line in service.rsplit("}", 1)[0].splitlines() if not line.lstrip().startswith("//"))
    methods = METHOD.findall(service)
    if not methods:
        raise SystemExit(f"no methods in {file}")
    names.update(name for name, _ in methods)
    parts[role] = (types, methods)

output = ["// Generated by scripts/build-single-candid.py; do not edit by hand."]
methods = []
for role, (types, entries) in parts.items():
    if role == "guard":
        continue
    symbols = TYPE.findall(types)
    for symbol in sorted(symbols, key=len, reverse=True):
        types = re.sub(rf"\b{symbol}\b", f"{role}_{symbol}", types)
    output.append(types.strip())
    for name, signature in entries:
        if name in {
            "set_vault_principal", "set_core_principal", "set_policy_principal",
            "set_send_journal", "set_journal_guard", "get_journal_guard",
            "set_sns_principal", "set_operator", "set_guard_principal",
            "get_role_principal", "register_budget_worker", "register_worker",
        }:
            continue
        for symbol in sorted(symbols, key=len, reverse=True):
            signature = re.sub(rf"\b{symbol}\b", f"{role}_{symbol}", signature)
        exported = f"{role}_{name}" if names[name] > 1 else name
        if role == "vault" and name == "transform_info":
            exported = "vault_transform_info"
        if role == "core" and name == "transform_info":
            exported = "transform_info"
        methods.append((exported, signature))
        if role == "journal" and name in {
            "head", "records", "intent_record", "append", "append_prepared",
            "authorize_send", "cancel_prepared_send", "recovery_head",
            "recovery_events", "recovery_event", "append_recovery_event",
        }:
            assert signature.startswith("("), signature
            suffix = signature[1:]
            args = "text" if suffix.startswith(")") else "text, "
            methods.append((f"role_{name}", f"({args}{suffix}"))

exported_names = [name for name, _ in methods]
if len(exported_names) != len(set(exported_names)):
    raise SystemExit("duplicate method in unified Candid")
output.append("service : (principal) -> {")
output.append("  application_administrator : () -> (principal) query;")
output.extend(f"  {name} : {signature};" for name, signature in sorted(methods))
output.append("}")
target = ROOT / "candid" / "private_perp.did"
target.write_text("\n\n".join(output) + "\n")
print(target)
